# This file was *autogenerated* from the file r01_3.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from sympy import *
from sage.all_cmdline import misc #sage.all_cmdline.misc probably collides with misc from sympy, it works with this fix
def f(z): return sqrt(_sage_const_1 /_sage_const_3 )*z**_sage_const_2  + I/_sage_const_3 
__time__=misc.cputime(); __wall__=misc.walltime(); e = f(f(f(f(f(f(f(f(f(f(I/_sage_const_2 )))))))))).as_real_imag()[int(_sage_const_0 )]; print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
