# This file was *autogenerated* from the file r01_1.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
def f(z): 
    return sqrt(_sage_const_1 /_sage_const_3 )*z**_sage_const_2  + i/_sage_const_3 
__time__=misc.cputime(); __wall__=misc.walltime(); real(f(f(f(f(i/_sage_const_2 ))))); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
