# This file was *autogenerated* from the file r02_3.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_15 = Integer(15)
__time__=misc.cputime(); __wall__=misc.walltime(); hermite(_sage_const_15 , polygen(ZZ)); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
