# This file was *autogenerated* from the file r03.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_10 = Integer(10)
var('x,y,z')
f = x+y+z
__time__=misc.cputime(); __wall__=misc.walltime(); a = [bool(f==f) for _ in range(_sage_const_10 )]; print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
