# This file was *autogenerated* from the file r04_2.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2)
u = [e, pi, sqrt(_sage_const_2 )]
__time__=misc.cputime(); __wall__=misc.walltime(); Tuples(u,_sage_const_3 ).cardinality(); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
