# This file was *autogenerated* from the file r06.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_100 = Integer(100)
__time__=misc.cputime(); __wall__=misc.walltime(); sum(((x+sin(i))/x+(x-sin(i))/x).rational_simplify() for i in xrange(_sage_const_100 )); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
