# This file was *autogenerated* from the file r07.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_32 = Integer(32); _sage_const_45 = Integer(45); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_18 = Integer(18); _sage_const_21 = Integer(21); _sage_const_34 = Integer(34); _sage_const_24 = Integer(24)
x=var('x') 
f = x**_sage_const_24 +_sage_const_34 *x**_sage_const_12 +_sage_const_45 *x**_sage_const_3 +_sage_const_9 *x**_sage_const_18  +_sage_const_34 *x**_sage_const_10 + _sage_const_32 *x**_sage_const_21 
__time__=misc.cputime(); __wall__=misc.walltime(); a = [f(x=random()) for _ in xrange(_sage_const_10 **_sage_const_4 )]; print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
