# This file was *autogenerated* from the file r09.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_20 = Integer(20); _sage_const_5 = Integer(5)
var('x,y')
__time__=misc.cputime(); __wall__=misc.walltime(); factor(x**_sage_const_20  - pi**_sage_const_5 *y**_sage_const_20 ); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
