# This file was *autogenerated* from the file r10.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
__time__=misc.cputime(); __wall__=misc.walltime(); v = (ellipsis_range(-pi,-pi+_sage_const_1 /_sage_const_10 ,Ellipsis,pi)); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
