# This file was *autogenerated* from the file r11.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000)
__time__=misc.cputime(); __wall__=misc.walltime(); a = [random() + random()*I for w in (ellipsis_range(_sage_const_0 ,Ellipsis,_sage_const_1000 ))]; print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
