# This file was *autogenerated* from the file s01.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_7 = Integer(7)
var('x,y,z')
f = (x+y+z+_sage_const_1 )**_sage_const_7 
__time__=misc.cputime(); __wall__=misc.walltime(); g = expand(f*(f+_sage_const_1 )); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
