# This file was *autogenerated* from the file s02_1.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_100 = Integer(100)
x,y,z=var('x,y,z')
__time__=misc.cputime(); __wall__=misc.walltime(); a = expand((x**sin(x) + y**cos(y) - z**(x+y))**_sage_const_100 ); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
