# This file was *autogenerated* from the file s03_8.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_50 = Integer(50)
from sympy import *
from sage.all_cmdline import misc
x,y,z=var('x,y,z')
g = expand((x**y+y**z+z**x)**_sage_const_50 )
h = g.diff(x)
__time__=misc.cputime(); __wall__=misc.walltime(); h = g.diff(x); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
