# This file was *autogenerated* from the file s03_7.sage.
from sage.all_cmdline import *   # import sage library
x,y,z=var('x,y,z')
g = maxima('expand((x^y+y^z+z^x)^50)')
__time__=misc.cputime(); __wall__=misc.walltime(); h = g.diff(z); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
