# This file was *autogenerated* from the file s03_4.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_500 = Integer(500)
x=var('x')
y=var('y')
z=var('z')
f=expand((x**y+y**z+z**x)**_sage_const_500 )
__time__=misc.cputime(); __wall__=misc.walltime(); g=f.diff(x); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
