# This file was *autogenerated* from the file s04_3.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000)
m = maxima(sin(x)*cos(x))
__time__=misc.cputime(); __wall__=misc.walltime(); w =m.taylor(x,_sage_const_0 ,_sage_const_1000 ); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
