# This file was *autogenerated* from the file s04_2.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1000 = Integer(1000)
x=var('x')
y=var('y')
__time__=misc.cputime(); __wall__=misc.walltime(); w = (sin(x)*cos(x)).series(x,_sage_const_1000 ); print "Time: CPU %.2f s, Wall: %.2f s"%(misc.cputime(__time__), misc.walltime(__wall__))
